function fnc_prog0_deleteSelection (varargin)
% MRI2PSM v0.1 - Patient-specific rigid body modeling from MRI images
% Copyright (c) 2016 Manish Sreenivasa <manish.sreenivasa@iwr.uni-heidelberg.de>, Daniel Gonzalez Alvarado, Carlos Javier Gonzalez Chamorro, Heidelberg University, Germany
%
% Licensed under the zlib license. See LICENSE for more details.
%

% Call variables from workspace
hardbone_segm = evalin ('base', 'hardbone_segm');
boneFat_segm  = evalin ('base', 'boneFat_segm');
muscle_segm   = evalin ('base', 'muscle_segm');
data_bmf      = evalin ('base', 'data_bmf');
currScanNr    = evalin ('base', 'currScanNr');
figure2       = evalin ('base', 'figure2');

% Refresh Plot
cla(figure2);
figure2 = subplot (1, 10, [2 7]);
axis equal; axis tight; hold on;
spy(boneFat_segm, 'y');
spy(muscle_segm, 'r');
spy(hardbone_segm, 'k');
title(['Scan Number:  ', num2str(currScanNr)])

% Define Buttons uicontrol
DrawSelection = uicontrol('style','text',...
    'unit','pix',...
    'position',[40 500 280 40],...
    'fontsize',12,...
    'fontweight','bold',...
    'string','Draw/Select');
SaveDrawSelection = uicontrol('style','pushbutton',...
    'unit','pix',...
    'position',[40 450 280 40],...
    'fontsize',12,...
    'fontweight','bold',...
    'string','Save',...
    'Callback',@fnc_prog0_saveDrawSelection);
Cancel = uicontrol('style','pushbutton',...
    'unit','pix',...
    'position',[40 400 280 40],...
    'fontsize',12,...
    'fontweight','bold',...
    'string','Cancel',...
    'Callback',@fnc_prog0_cancel);
NextScan = uicontrol('style','text',...
    'unit','pix',...
    'position',[40 350 280 40],...
    'fontsize',12,...
    'fontweight','bold',...
    'string','NextScan');
PreviousScan = uicontrol('style','text',...
    'unit','pix',...
    'position',[40 300 280 40],...
    'fontsize',12,...
    'fontweight','bold',...
    'string','PreviousScan');
DeleteSelection = uicontrol('style','text',...
    'unit','pix','position',[40 250 280 40],...
    'fontsize',12,...
    'fontweight','bold',...
    'string','Delete Selection');

deleteSelection = 1;

evalin ('base', 'deleteSelection = 1;')
evalin ('base', 'boundaries = [];')
assignin ('base', 'tmp_hardbone_segm', hardbone_segm);
assignin ('base', 'tmp_muscle_segm', muscle_segm);
assignin ('base', 'tmp_boneFat_segm', boneFat_segm);
assignin ('base', 'figure2', figure2);
end
